import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import { AppProvider } from "@/components/AppContext";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Head from "next/head";


const inter = Inter({ subsets: ["latin"] });


export default function RootLayout({ children }) {

  return (
    <>
      <Head>
      <title>Order Food Online from India`&apos;`s Best Food Delivery Service | Swiggy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <main>
          <AppProvider>
            <Header />
            {children}
          </AppProvider>
          <ToastContainer />
        </main>
      </body>
    </>

  );
}
