import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import { AppProvider } from "@/components/AppContext";

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (

    <html lang="en">
      <body>
        <main>
          <AppProvider>
          <Header />
            {children}
          </AppProvider>
          <ToastContainer />
        </main>
      </body>
    </html>

  );
}
